import { useState, useCallback } from 'react';
import { DeviceLocalStorage, LocalDevice } from '@/src/lib/localStorage';
import { useAuth } from '@/contexts/AuthContext';
import { compressDevicePhoto, compressReceipt } from '../lib/imageCompression';

export interface DeviceFormData {
  // Mandatory fields (user must provide)
  name: string;
  purchaseDate: Date | null;
  warrantyMonths: string;
  purchasePrice: string;
  receipt: { uri: string | null; type: 'camera' | 'library' | null };
  
  // Optional fields (user can leave blank, but fields stay visible)
  serialNumber: string;
  storeName: string;
  category: string; // Add category field
  devicePhoto: { uri: string | null; type: 'camera' | 'library' | null };
}

export const useDeviceSync = () => {
  const { user } = useAuth();
  const [isStoring, setIsStoring] = useState(false);

  const getLocalDevices = useCallback(async (): Promise<LocalDevice[]> => {
    try {
      return await DeviceLocalStorage.getDevices();
    } catch (error) {
      console.error('Error getting local devices:', error);
      return [];
    }
  }, []);

  const getDevicesByStatus = useCallback(async (status: LocalDevice['sync_status']): Promise<LocalDevice[]> => {
    try {
      return await DeviceLocalStorage.getDevicesByStatus(status);
    } catch (error) {
      console.error('Error getting devices by status:', error);
      return [];
    }
  }, []);

  const clearLocalData = useCallback(async (): Promise<void> => {
    try {
      console.log('Clearing local data...');
      await DeviceLocalStorage.clearAll();
      console.log('Local data cleared successfully');
    } catch (error) {
      console.error('Error clearing local data:', error);
    }
  }, []);



  // 2. Main functions that use the utilities above
  const addDevice = useCallback(async (formData: DeviceFormData): Promise<{
    success: boolean;
    localId?: string;
    message: string;
  }> => {
    if (!user?.id) {
      return { success: false, message: 'User not authenticated' };
    }

    console.log('Starting addDevice with formData:', formData);
    console.log('User ID:', user.id);

    try {
      setIsStoring(true);

      // Validate required fields
      if (!formData.name.trim()) {
        return { success: false, message: 'Device name is required' };
      }
      if (!formData.purchaseDate) {
        return { success: false, message: 'Purchase date is required' };
      }
      if (!formData.warrantyMonths.trim()) {
        return { success: false, message: 'Warranty duration is required' };
      }
      if (!formData.receipt.uri) {
        return { success: false, message: 'Receipt is required' };
      }

      // Calculate warranty end date
      const warrantyMonths = parseInt(formData.warrantyMonths);
      if (isNaN(warrantyMonths) || warrantyMonths <= 0) {
        return { success: false, message: 'Invalid warranty duration' };
      }

      const purchaseDate = new Date(formData.purchaseDate);
      const warrantyEndDate = new Date(purchaseDate);
      warrantyEndDate.setMonth(warrantyEndDate.getMonth() + warrantyMonths);

      // 1. Compress images first (for both local storage AND upload)
      let compressedPhoto = null;
      let compressedReceipt = null;
      
      if (formData.devicePhoto?.uri) {
        console.log('Compressing device photo...');
        compressedPhoto = await compressDevicePhoto(formData.devicePhoto.uri);
        console.log('Device photo compressed successfully');
      }
      
      if (formData.receipt?.uri) {
        console.log('Compressing receipt...');
        compressedReceipt = await compressReceipt(formData.receipt.uri);
        console.log('Receipt compressed successfully');
      }

      // 2. Create device object with compressed images
      const deviceData: Omit<LocalDevice, 'sync_status' | 'local_id'> = {
        id: '', // Will be generated by database
        user_id: user.id,
        name: formData.name.trim(),
        supplier: formData.storeName.trim() || null,
        category: formData.category.trim() || null, // Add category field
        purchase_date: purchaseDate.toISOString().split('T')[0], // YYYY-MM-DD format
        warranty_months: warrantyMonths,
        warranty_end_date: warrantyEndDate.toISOString().split('T')[0],
        purchase_price: formData.purchasePrice ? parseFloat(formData.purchasePrice) : null,
        location: null, // Not used
        photo_irl: compressedPhoto, // Store compressed image
        notes: null, // Not used
        invoice_url: compressedReceipt, // Store compressed receipt
        identifiers: formData.serialNumber.trim() || null,
        created_at: new Date().toISOString(),
      };

      // 3. Store locally with compressed images (should be ~50KB each)
      console.log('Storing device locally with compressed images...');
      const localId = await DeviceLocalStorage.storeDevice(deviceData);
      
      console.log('Device stored locally with ID:', localId);



      return {
        success: true,
        localId,
        message: 'Device added successfully!',
      };

    } catch (error) {
      console.error('Error adding device:', error);
      return {
        success: false,
        message: 'Failed to add device. Please try again.',
      };
    } finally {
      setIsStoring(false);
    }
  }, [user?.id]);

  return {
    // State
    isStoring,
    
    // Actions
    addDevice,
    
    // Data
    getLocalDevices,
    getDevicesByStatus,
    
    // Utility
    clearLocalData,
  };
};
